language: php
php:
  - 5.6
  - 5.5
  - '7'
  - hhvm
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
script:
  - composer test
after_script:
  - composer coveralls
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
notifications:
  email: false
sudo: false
