[target]

# Include source files.
includes = ["src"]
 
# Exclude source files.
excludes = ["vendor", "spec"]

[report.coverageBounds]
satisfactory = 80.0
critical = 50.0

[reporter]

# TreeReporter
[reporter.tree]

# ProcessingTimeReporter
[reporter.processingTime]
